### ISSUE TITLE
Github Pages

### ISSUE THREAD

**Issue by ghost** [REBECANONATO/CoresRGB#2]
Oi Rebeca

Eu também sou um desenvolvedor.

Eu estou escrevendo porque acho que esse projeto merece estar online, e você pode configurar isso facilmente.

O github hospeda páginas estáticas gratuítamente. É o caso desse projeto.
Para ativar, basta clicar em 'settings' ou 'configurações', na página principal do projeto. Daí, na página de configurações tem a opção 'Github Pages'

É de graça

**Comment by rebecanonato89** [comment]
Ei, 

agradeço a consideração.

Disponibilizei ele em: https://rebecanonato89coresrgb.netlify.app/

tentei pelo github que vc indicou, porém ainda não consegui. 
Irei verificar.

**Comment by rebecanonato89** [comment]
Deu certo

https://rebecanonato89.github.io/CoresRGB/
